# Generated by Django 4.1 on 2022-08-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_delete_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
